name: CI/CD Angular Firebase NovaTienda

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npx ng build --configuration production

      - name: Deploy to Firebase
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: npx firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
